module.exports = `
                              ...............                                                       
                          .......................                                                   
                      ..............................                                                
                   ............    ....................                                             
                  .............            ...............                                          
                ...............                .............                                        
               ..............                   .............                                       
              :............                      .............                                      
             ..............                       ............                                      
            ...............                    ................                                     
            :..............                   .................                                     
            :..............                   ..................                                    
            ............................. ../+/:................                                    
            .:..../ooso++............../oyhhhhhhyy+:............                                    
            ....+hhhyhdddhhhyo+..../ssyhhdhhys+++oyss/... ......                                    
            +yyosy+........:/+shyysydy+::.:/ooo/..../dmdyso+/:..                                    
         ...+dd.....:/ommmy.:..ydysdm.. ./.oddh/.... +NNNmmdhhyo....                                
         /....h.........::.....d....y+..        .... yy......../.:.:.                               
         :o/..:+..............h......s/..      ...../h...........:./.                               
         :o....:o+/::::://++++........o+/.........:++........../..:o.                               
         :+..+............................::///::............./.:..:                                
         ./.::.........................           ...............:.:                                
          +.:/............./...........           ................:.                                
          ./.:.......................          .  .................                                 
            :.:......................          ...  .............                                   
             :/.............:////:::::......... ............:...                                    
              :........../syo+//:::..:://oo/...  .. ..........                                      
              ..............++++//::::....       .............                                      
               .............                    . ............                                      
                .............                        .........                                      
                 ...........                        ........:.                                      
                   .........                      ..........:                                       
                    .:......                    ............/.                                      
                     ........           .  .................:...                                    
                      :......................................:....so/.                              
                      .......................     .  ......../.....yddds:                           
                       ...................               ....:.....hmmdyyo/:.                       
                   ../oy:.............                    ........:mmmdyyyyyhy+..                   
               ../yyyhdhy.............    .               ........hmmdyysshhhyo+o+/:.               
           .:+o+oyhyhdhhd.......:.. ........              .......sddhyhyyhdhysoosyyso+:..           
       ..:+shhssyhhhdhhddo...................            ......+hdhyhhyhddhssssyyyo+++ooyo:.        
    ..oyooshhyyyhddhhhdmdd...........................    ....ohdhhyhdddddhyssyyys++ossyysso+:..     
  ./syysoshhhysyddhyhydmmdy.............................../ydddhyyysyddddyyyhhyo++syyso+++oooo+..   
 ..oyyyooyyhyshddyyoshddmddh+........................./ohdmddhyysoosyyhddhyhhyo+ossso+++ssyyso/:....
  :ssysooyhhhhyyososyhhhyhddddy+:.................+shdddddhyyyyssooosssydddhsoosyso+/+oyyso/..  ....
  .+yyo+oyhyyso+syyssssyyyhhhdddddhso++///++osyhddddddhhyyyyyyyyso++++ooyhhyooyyso++syys+...        
   ..:+ssyo+osyyysssyyyyyyyyhhhdddddddddddmdddddddhhhyyyyyyyyyyysso+++++oyddsyyso+ssso/.....        
     ./+ooosyhhyyyyyyyyyyhhyyhhhhdddddddddddhhhhyyyyhyyyyyyyyysssoo++//+++syyso//o+:.               
      .:ossssso////++/:://oyyyyyyyysyyyyyyyyyssoooo+osyyyysso+ooooo++++/:::::.  ...                 
`;
